### ISSUE TITLE
pzbot_js should not care about a username's case for comparison purposes

### ISSUE THREAD

**Issue by djaggie** [fluffigvarg/pzbot_js#1]
pzbot should not care about a username's case. Comparing the db entries to the user should match on any cases.
pzbot should still respond with a user's proper case in chat.

Example:
user "Nightbot" should match blocked list entry "niGhtBoT" for durrring purposes

Prawnzbot: Hey Duffman, you owe 0 bits!

**Comment by fluffigvarg** [comment]
Thank you! I refactored the code so it uses Twitch User ID as the main form of identification.
